from django.urls import path
from .views import (
    InicioView,
    AcercaView,
    TiendaView,
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    GuiaListView,
    GuiaDetailView,
    EventoListView,
    DescargaListView,
    RankingListView,
    LoginUsuarioView,
    LogoutUsuarioView,
    registro,
    perfil,
    editar_perfil,
    contacto,
)

urlpatterns = [
    path("", InicioView.as_view(), name="inicio"),
    path("acerca/", AcercaView.as_view(), name="acerca"),
    path("noticias/", PostListView.as_view(), name="post_list"),
    path("noticias/<int:pk>/", PostDetailView.as_view(), name="post_detalle"),
    path("noticias/crear/", PostCreateView.as_view(), name="post_crear"),
    path("noticias/<int:pk>/editar/", PostUpdateView.as_view(), name="post_editar"),
    path("noticias/<int:pk>/eliminar/", PostDeleteView.as_view(), name="post_eliminar"),
    path("guias/", GuiaListView.as_view(), name="guia_list"),
    path("guias/<int:pk>/", GuiaDetailView.as_view(), name="guia_detalle"),
    path("eventos/", EventoListView.as_view(), name="evento_list"),
    path("descargas/", DescargaListView.as_view(), name="descarga_list"),
    path("ranking/", RankingListView.as_view(), name="ranking"),
    path("tienda/", TiendaView.as_view(), name="tienda"),
    path("contacto/", contacto, name="contacto"),
    path("registro/", registro, name="registro"),
    path("login/", LoginUsuarioView.as_view(), name="login"),
    path("logout/", LogoutUsuarioView.as_view(), name="logout"),
    path("perfil/", perfil, name="perfil"),
    path("perfil/editar/", editar_perfil, name="editar_perfil"),
]
